steps:
- name: 'alpine:3.20'
  entrypoint: 'sh'
  args:
  - '-c'
  - 'echo "SECRET=${_TEST_SECRET} TOKEN=${_INTERNAL_TOKEN} BRANCH=${_BRANCH_NAME}"'
substitutions:
  _BRANCH_NAME: "default_branch"
  _TEST_SECRET: "DEFAULT_NOT_SET"
  _INTERNAL_TOKEN: "DEFAULT_NOT_SET"
options:
  logging: CLOUD_LOGGING_ONLY
